services:
  postgres:
    image: postgres:latest
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${NAME_DB}
    volumes:
      - /var/lib/postgresql
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSwORD}
    ports:
      - '${ADMIN_PORT}:80'
    depends_on:
        - postgres
    networks:
      - pgnetwork

volumes:
  postgres_data:

networks:
  pgnetwork: